### ISSUE TITLE
Sleep Commands in Script

### ISSUE THREAD

**Issue by elliot-huffman** [johnnyapol/RootMyValet#14]
I was talking with my friend who works on supercomputers and he noticed the sleep commands.

Why are those there? He says that they are a wast of time to put them in.

Is there any special reason why there there?

**Comment by johnnyapol** [comment]
I kept the delay in when I modified the root script because for some reason telnet was being funky if I just sent the commands.

**Comment by elliot-huffman** [comment]
Hmmm... ok...
