### ISSUE TITLE
can i please get help for my root ??

### ISSUE THREAD

**Issue by nthlogik** [johnnyapol/RootMyValet#22]
i was wondering.... could someone please help me understand how to gain root access to my ZTE z665c (valet) ..... i have tried several apps but they don't seem to work. could someone possibly explain
to me step by step how to do this ? i'd be ever so grateful...

**Comment by nthlogik** [comment]
much apologies if this comment is not in the right place......

**Comment by elliot-huffman** [comment]
Check out this page:
http://androidforums.com/threads/ill-help-find-a-root-method-if.799676/

I am pretty sure that this phone has been considered "unrootable"
