### ISSUE TITLE
Push.sh

### ISSUE THREAD

**Issue by elliot-huffman** [johnnyapol/RootMyValet#5]
There is now push.sh file present in the code. Could you please add it so rooting can continue as normal?

**Comment by elliot-huffman** [comment]
I noticed in the Windows batch file that it referenced installsu.sh file and not push.sh file. Was there an update in which the file name was changed?

**Comment by johnnyapol** [comment]
Done thank you.

**Comment by johnnyapol** [comment]
Oops, push.sh was an old script file, I fixed the issue.
