### ISSUE TITLE
Not rooting

### ISSUE THREAD

**Issue by elliot-huffman** [johnnyapol/RootMyValet#6]
I have installed and run the "push su" button but it has not rooted the device.
I have rebooted the device and checked again but no luck.
I pushed roothandeler, installsu.sh and su to the /data/local/tmp folder and chmoded the roothandeler and installsu.sh flile.

I am using a ZTE 665c.

**Comment by johnnyapol** [comment]
Unfortantely without a stack trace or any other log I cannot give a definite answer. I'll try the test ASAP and see what I can do.

**Comment by elliot-huffman** [comment]
What can I do to test it? I have installed the apk and pushed the required files...

**Comment by johnnyapol** [comment]
I have to test either tonight or tomorrow night and figured out what went wrong. I'll respond when with my findings. :) 

@elliot-labs

**Comment by elliot-huffman** [comment]
@Unkn0wn0ne Thanks! Is there a chat system so I can directly communicate to you?

**Comment by johnnyapol** [comment]
@elliot-labs  Not sure yet. I fixed some issues with a script that I will be committing shortly

**Comment by johnnyapol** [comment]
I did it! The commit fixed it. I rooted the phone.

**Comment by johnnyapol** [comment]
@elliot-labs 

I'm sure you'll be as happy as I am, it's a little cut off, but it's there.
http://i.imgur.com/QTRU1Cz.png?1

**Comment by elliot-huffman** [comment]
wow! I am going to have to try the updated files!

On Mon, May 12, 2014 at 7:59 PM, John notifications@github.com wrote:

> @elliot-labs https://github.com/elliot-labs
> 
> I'm sure you'll be as happy as I am, it's a little cut off, but it's there.
> http://i.imgur.com/QTRU1Cz.png?1
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Unkn0wn0ne/RootMyValet/issues/6#issuecomment-42903235
> .

## 

Elliot

DISCLAIMER:
This e-mail is for the intended recipient(s) only

If you have received it by mistake please let me know by reply and then
delete it from your system; access, disclosure, copying, distribution or
reliance on any of it by anyone else is prohibited.

If you as intended recipient have received this e-mail incorrectly, please
notify the sender (via e-mail) immediately.

**Comment by benjimt** [comment]
@Unkn0wn0ne I have tried doing the steps in your install.txt file, but when i tap "Push SU Binary" it says, "Starting binary push...." then nothing happens. I have installed Superuser but is says it cant find the binary. I have rebooted the device a few times and then repeated, but I got the same result. Any suggestions?

**Comment by johnnyapol** [comment]
@benjimt 

Right now I have tested it by doing on my computer adb shell and than entering cd /data/local/tmp and than ./roothandler, I'll have to try the app later.

**Comment by benjimt** [comment]
![sshot1](https://cloud.githubusercontent.com/assets/7563744/2952325/1336589c-da39-11e3-923b-5c5a096d1c76.jpg)
I am getting this strange error when I try that.

??

**Comment by elliot-huffman** [comment]
I am getting this error:

shell@android:/data/local/tmp $ ls
ls
installsu.sh
roothandler
su
shell@android:/data/local/tmp $ chmod 0755 installsu.sh
chmod 0755 installsu.sh
shell@android:/data/local/tmp $ ./roothandler
./roothandler
ro.build.product=seanplus
ro.build.id=JRO03C
search kallsyms...
1 2 3 4 5 6 7 8 9 10 11 12
(kallsyms_addresses=c066fba0)
(kallsyms_num_syms=00010e24)
kernel dump...
1 2 3 4 5 6 7 8 9

prepare_kernel_cred=c00b14c8
commit_creds=c00b113c
ptmx_fops=c09f5698

Succeeded in getroot!
RootMyValet root script for Android devices
' unexpectedtmp/installsu.sh[14]: syntax error: '\

**Comment by johnnyapol** [comment]
Try the new installsu.sh up now please and report back and reopen. I'll try fixing the issues with the app at a later date.

**Comment by johnnyapol** [comment]
The issue with the Android app not working has been migrated to #9 as the actual rooting function does work now but for whatever reason not the app. I will try to get a fix out but I don't have to ability to tonight.

**Comment by benjimt** [comment]
@Unkn0wn0ne The new installsu.sh still has this error for me:

Succeeded in getroot!
RootMyValet root script for Android devices
' unexpectedtmp/installsu.sh[14]: syntax error: '\

If there is anything I can do to help, let me know.

Thanks for your great work on this cheap phone!
